version: '2.1'

services:
  test:
    build: .
    entrypoint: npm test
    volumes:
      - .:/usr/src/saudify
      - /usr/src/saudify/node_modules
    environment:
      MONGO_URI: mongodb://mongo/saudify
      SERVER_PORT: 3000
    depends_on:
      saudify-api:
        condition: service_started

  saudify-api:
    build: .
    command: node src/index.js
    volumes:
      - .:/usr/src/saudify
      - /usr/src/saudify/node_modules
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo/saudify
      SERVER_PORT: 3000
    depends_on:
      mongo:
        condition: service_started
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db
