version: '2.1'

services:
  saudify-api:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/saudify
      - /usr/src/saudify/node_modules
      - /usr/src/saudify/certs
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo/saudify
      SERVER_PORT: 3000
    depends_on:
      mongo:
        condition: service_started
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db
